apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: kafka
  labels:
    service: kafka
spec:
  type: NodePort
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka
