apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  labels:
    service: kafka-ui
spec:
  ports:
    - name: kafka-ui
      port: 80
      targetPort: 9000
  type: LoadBalancer
  selector:
    app: kafka-ui
