apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-zookeeper-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: data-zookeeper-0
  hostPath:
    path: "/tmp/zookeeper-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-zookeeper-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: data-zookeeper-1
  hostPath:
    path: "/tmp/zookeeper-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-zookeeper-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: data-zookeeper-2
  hostPath:
    path: "/tmp/zookeeper-2"

