---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-zookeeper-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: zookeeper
      podindex: "0"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-zookeeper-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: zookeeper
      podindex: "1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-zookeeper-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: zookeeper
      podindex: "2"
